version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4444:4444
    command: npm start
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data:
